name: Run Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install NeoVim
        run: |
          curl -sL -o nvim https://github.com/neovim/neovim/releases/download/v0.12.2/nvim-linux-x86_64.appimage
          chmod u+x nvim
          sudo mv nvim /usr/local/bin
          nvim --version
      - name: Run tests from makefile
        run: make test


